name: Build and Export IPA

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: macOS-latest  # Use the latest macOS runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable  # Use the latest stable version of Xcode

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          brew install carthage  # Example: Install Carthage for dependency management
          carthage bootstrap --platform iOS

      # Step 4: Build and Archive the project
      - name: Build and Archive
        run: |
          xcodebuild -scheme YourAppScheme -destination 'generic/platform=iOS' -archivePath YourApp.xcarchive archive

      # Step 5: Export the IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath YourApp.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist

      # Step 6: Upload the IPA as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: YourApp.ipa
          path: YourApp.ipa
